# Generated by Django 6.0.1 on 2026-02-26 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0002_scheduletemplate_schedule_schedule_template_and_more"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="schedules.scheduletemplate",
            ),
        ),
    ]
