# Generated by Django 6.0.1 on 2026-03-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0002_scheduletemplate_schedule_schedule_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="days_of_week",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
